In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score 
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import confusion_matrix

from sklearn.feature_selection import SelectFromModel

In [3]:
#Exploración de los datos
#reg = linear_model.LogisticRegression()

df = pd.read_csv("Documentsporcentajes.csv")

In [4]:
reduce = lambda x: round(x, 3)
lstx = df[df.columns[:-6]]
for col in lstx.keys():
    lstx[col] = lstx[col].apply(reduce)
lstx = lstx.to_numpy()
coso = {'Pass': 1 , 'Fail': 0}
lsty = df[df.columns[-1]].map(coso).to_numpy()


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [5]:
lsty

array([1, 0, 0, ..., 1, 0, 0])

In [6]:
#Datos de entrenamiento y prueba 
x_train , x_test, y_train, y_test = train_test_split(lstx, lsty)

In [7]:
sel = SelectFromModel(LinearRegression())

In [8]:
sel.fit(x_train, y_train)

SelectFromModel(estimator=LinearRegression(copy_X=True, fit_intercept=True,
                                           n_jobs=None, normalize=False),
                max_features=None, norm_order=1, prefit=False, threshold=None)

In [9]:
sel.get_support()

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True,  True,  True])

In [10]:
sel.estimator_.coef_

array([-2.07176727e-01, -1.21083759e-01, -4.68676307e-01, -1.54878444e-01,
       -7.96137514e-01, -4.80360542e-01,  2.99936931e+00, -2.57843668e+00,
       -1.56447189e+00,  1.01335674e+00, -1.23775403e+00,  1.29853518e+00,
        2.77419529e+01,  1.66629155e+00,  2.93098879e-14, -9.26966204e+00,
       -1.41871604e-01,  4.46879488e-01,  1.88227766e+00,  1.74941694e+02,
        6.47269509e+01,  6.51596140e+01])

In [13]:
mean = np.mean(np.abs(sel.estimator_.coef_))
mean

16.313519600774967

### L1 Logistic Regression Coefficient with L1 Regularization 

In [14]:
sel = SelectFromModel(LogisticRegression(penalty = 'l1', C =10 , solver = 'liblinear'))

In [15]:
sel.fit(x_train, y_train)

SelectFromModel(estimator=LogisticRegression(C=10, class_weight=None,
                                             dual=False, fit_intercept=True,
                                             intercept_scaling=1, l1_ratio=None,
                                             max_iter=100, multi_class='auto',
                                             n_jobs=None, penalty='l1',
                                             random_state=None,
                                             solver='liblinear', tol=0.0001,
                                             verbose=0, warm_start=False),
                max_features=None, norm_order=1, prefit=False, threshold=None)

In [16]:
sel.get_support()

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True])

In [17]:
sel.estimator_.coef_

array([[-6.99455215e-01,  3.32781228e-01, -2.51810198e+00,
         1.36823687e-01, -1.45817979e+00, -2.34020787e+00,
         0.00000000e+00, -1.35749358e+02,  9.96091456e+00,
         4.10186386e+00, -1.47994224e+02,  1.84964179e+01,
         1.24365912e+02,  4.97910905e+00,  0.00000000e+00,
        -2.84886743e+01,  0.00000000e+00,  1.80386537e+00,
         1.18123753e+01,  6.31447644e+02, -4.27941954e+00,
         4.73065357e-01]])

In [18]:
np.mean(np.abs(sel.estimator_.coef_))

51.429017896168425

### Explicar la division de los sets de datos, los tipos de validacion, accuracy del modelo 